spring.application.name=assignment-webbteknik
logging.level.root=INFO
logging.level.org.springframework.security=INFO
logging.level.org.springframework.boot.security=DEBUG
spring.security.user.name=user
spring.security.user.password=password
